Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -3,6 +3,23 @@ pipeline {
 
     stages {
 
+        stage('Install Node.js') {
+            steps {
+                script {
+                    // Install Node.js and npm if not installed
+                    sh '''
+                        if ! command -v node &> /dev/null; then
+                            echo "Node.js not found. Installing..."
+                            sudo apt update
+                            sudo apt install -y nodejs npm
+                        else
+                            echo "Node.js is already installed."
+                        fi
+                    '''
+                }
+            }
+        }
+
         stage('Install Dependencies') {
             steps {
                 script {
